spring:
  datasource:
    username: root
    password: 140429
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictabIdleTimeMillis: 30000
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
      #    配置数据监控统计拦截
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true

  security:
    user:
      name: u
      password: u



server:
  port: 8080  # 配置项目访问的端口号
#  servlet:
#    context-path: /  # 配置项目访问路径
mybatis:
  configuration:
    use-generated-keys: true
